version: '3'

services:
  frontend:
    build:
      context: ./frontend  # Path to your Next.js app directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose Next.js frontend on port 3000
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend  # Path to your Node.js backend directory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Expose Node.js backend on port 3001
    environment:
      - NODE_ENV=production
